In [9]:
import pandas as pd

data_path = "/Users/philippjohn/Developer/youtube-analytics-data/"

car_1 = "Porsche_911_GT3​"
df_1 = pd.read_csv(data_path + car_1 + "/feature_stats.csv", header=[0], lineterminator='\n')
df_1 = df_1.drop(['Unnamed: 0'], axis=1, errors='ignore')
df_1

           feature  comment_count  sentiment_mean
0       suspension              2        4.500000
1          gearbox              6        4.333333
2            brake              1        4.000000
3           design              8        3.750000
4           engine             50        3.720000
5            sound             46        3.717391
6   steering wheel              1        3.000000
7            color              4        3.000000
8            light             10        3.000000
9             body              7        3.000000
10        exterior              1        2.000000

In [10]:
import pandas as pd

data_path = "/Users/philippjohn/Developer/youtube-analytics-data/"

car_2 = "Porsche_911_Sport_Classic​"
df_2 = pd.read_csv(data_path + car_2 + "/feature_stats.csv", header=[0], lineterminator='\n')
df_2 = df_2.drop(['Unnamed: 0'], axis=1, errors='ignore')
df_2

         feature  comment_count  sentiment_mean
0         mirror              1        5.000000
1          color              3        4.333333
2       interior              9        4.222222
3          sound             19        4.210526
4         engine             15        4.066667
5         colour              2        4.000000
6       exterior              1        4.000000
7     navigation              1        4.000000
8        gearbox              9        3.888889
9         design             24        3.666667
10           rim              7        3.142857
11    suspension              1        3.000000
12  infotainment              1        3.000000
13          body             18        2.944444
14         light              7        2.000000

In [15]:
import pandas as pd
df = pd.merge(df_1, df_2, on="feature", how="inner")
df

,feature,comment_count_x,sentiment_mean_x,comment_count_y,sentiment_mean_y
0,suspension,2,4.500000,1,3.000000
1,gearbox,6,4.333333,9,3.888889
2,design,8,3.750000,24,3.666667
3,engine,50,3.720000,15,4.066667
4,sound,46,3.717391,19,4.210526
5,color,4,3.000000,3,4.333333
6,light,10,3.000000,7,2.000000
7,body,7,3.000000,18,2.944444
8,exterior,1,2.000000,1,4.000000

In [17]:
categories = df['feature'].tolist()
categories

['suspension',
 'gearbox',
 'design',
 'engine',
 'sound',
 'color',
 'light',
 'body',
 'exterior']

In [18]:
car_1_sentiment = df['sentiment_mean_x'].tolist()
car_1_sentiment

[4.5, 4.333333333333333, 3.75, 3.72, 3.717391304347826, 3.0, 3.0, 3.0, 2.0]

In [20]:
# Get df 1
df_1 = pd.read_csv(data_path + car_1 + "/feature_stats.csv", header=[0], lineterminator='\n')
df_1 = df_1.drop(['Unnamed: 0'], axis=1, errors='ignore')
df_1['car'] = car_1

# Get df 2
df_2 = pd.read_csv(data_path + car_2 + "/feature_stats.csv", header=[0], lineterminator='\n')
df_2 = df_2.drop(['Unnamed: 0'], axis=1, errors='ignore')
df_2['car'] = car_2

# Merge (inner) df 1 and df 2
df = pd.merge(df_1, df_2, on="feature", how="inner")
print(df.head())

      feature  comment_count_x  sentiment_mean_x             car_x  \
0  suspension                2          4.500000  Porsche_911_GT3​
1     gearbox                6          4.333333  Porsche_911_GT3​
2      design                8          3.750000  Porsche_911_GT3​
3      engine               50          3.720000  Porsche_911_GT3​
4       sound               46          3.717391  Porsche_911_GT3​

   comment_count_y  sentiment_mean_y                       car_y
0                1          3.000000  Porsche_911_Sport_Classic​
1                9          3.888889  Porsche_911_Sport_Classic​
2               24          3.666667  Porsche_911_Sport_Classic​
3               15          4.066667  Porsche_911_Sport_Classic​
4               19          4.210526  Porsche_911_Sport_Classic​

In [40]:
# Get df 1
df_1 = pd.read_csv(data_path + car_1 + "/feature_stats.csv", header=[0], lineterminator='\n')
df_1 = df_1.drop(['Unnamed: 0'], axis=1, errors='ignore')
df_1['car'] = car_1

# Get df 2
df_2 = pd.read_csv(data_path + car_2 + "/feature_stats.csv", header=[0], lineterminator='\n')
df_2 = df_2.drop(['Unnamed: 0'], axis=1, errors='ignore')
df_2['car'] = car_2

# Merge (inner) df 1 and df 2
df = pd.concat([df_1, df_2])
df = df[df.groupby('feature')["feature"].transform(len) > 1]
df.insert(0, 'car', df.pop('car'))
print(df.head(n=50))

                           car     feature  comment_count  sentiment_mean
0             Porsche_911_GT3​  suspension              2        4.500000
1             Porsche_911_GT3​     gearbox              6        4.333333
3             Porsche_911_GT3​      design              8        3.750000
4             Porsche_911_GT3​      engine             50        3.720000
5             Porsche_911_GT3​       sound             46        3.717391
7             Porsche_911_GT3​       color              4        3.000000
8             Porsche_911_GT3​       light             10        3.000000
9             Porsche_911_GT3​        body              7        3.000000
10            Porsche_911_GT3​    exterior              1        2.000000
1   Porsche_911_Sport_Classic​       color              3        4.333333
3   Porsche_911_Sport_Classic​       sound             19        4.210526
4   Porsche_911_Sport_Classic​      engine             15        4.066667
6   Porsche_911_Sport_Classic​    exterior              1        4.000000
8   Porsche_911_Sport_Classic​     gearbox              9        3.888889
9   Porsche_911_Sport_Classic​      design             24        3.666667
11  Porsche_911_Sport_Classic​  suspension              1        3.000000
13  Porsche_911_Sport_Classic​        body             18        2.944444
14  Porsche_911_Sport_Classic​       light              7        2.000000

In [50]:
import pandas as pd

data_path = "/Users/philippjohn/Developer/youtube-analytics-data/"

cars = ["Porsche_911_GT3​",
        "Porsche_911_Sport_Classic​"]

df = pd.DataFrame()

if len(cars) == 0:
    print("Please input at least one car")
else:
    for car in cars:
        df_car = pd.read_csv(data_path + car + "/feature_stats.csv", lineterminator='\n')
        df_car = df_car.drop(['Unnamed: 0'], axis=1, errors='ignore')
        df_car['car'] = car
        df = pd.concat([df, df_car])

df = df.reset_index(drop=True)
df

           feature  comment_count  sentiment_mean                         car
0       suspension              2        4.500000            Porsche_911_GT3​
1          gearbox              6        4.333333            Porsche_911_GT3​
2            brake              1        4.000000            Porsche_911_GT3​
3           design              8        3.750000            Porsche_911_GT3​
4           engine             50        3.720000            Porsche_911_GT3​
5            sound             46        3.717391            Porsche_911_GT3​
6   steering wheel              1        3.000000            Porsche_911_GT3​
7            color              4        3.000000            Porsche_911_GT3​
8            light             10        3.000000            Porsche_911_GT3​
9             body              7        3.000000            Porsche_911_GT3​
10        exterior              1        2.000000            Porsche_911_GT3​
11          mirror              1        5.000000  Porsche_911_Sport_Classic​
12           color              3        4.333333  Porsche_911_Sport_Classic​
13        interior              9        4.222222  Porsche_911_Sport_Classic​
14           sound             19        4.210526  Porsche_911_Sport_Classic​
15          engine             15        4.066667  Porsche_911_Sport_Classic​
16          colour              2        4.000000  Porsche_911_Sport_Classic​
17        exterior              1        4.000000  Porsche_911_Sport_Classic​
18      navigation              1        4.000000  Porsche_911_Sport_Classic​
19         gearbox              9        3.888889  Porsche_911_Sport_Classic​
20          design             24        3.666667  Porsche_911_Sport_Classic​
21             rim              7        3.142857  Porsche_911_Sport_Classic​
22      suspension              1        3.000000  Porsche_911_Sport_Classic​
23    infotainment              1        3.000000  Porsche_911_Sport_Classic​
24            body             18        2.944444  Porsche_911_Sport_Classic​
25           light              7        2.000000  Porsche_911_Sport_Classic​